# Generated by Cursor AI on 2026-03-19

from django.db import migrations


def seed_academy_data(apps, schema_editor):
    Course = apps.get_model("core", "Course")
    Timetable = apps.get_model("core", "Timetable")
    Instructor = apps.get_model("core", "Instructor")

    # Old DB rows were forced to use a default Course.name during migration.
    # Deactivate those placeholders so they don't clutter the selection UI.
    Course.objects.filter(name="Course").update(is_active=False)

    courses_data = [
        {
            "name": "Bharatanatyam",
            "description": "A classical dance form known for expressive facial expressions, precise footwork, and elegant hand gestures (mudras).",
            "duration": "1 hour per session",
            "fee": 1000,
        },
        {
            "name": "Mohiniyattam",
            "description": "A graceful classical dance form from Kerala with soft movements and expressive storytelling.",
            "duration": "1 hour per session",
            "fee": 1000,
        },
        {
            "name": "Kuchipudi",
            "description": "An energetic classical dance form from Andhra Pradesh with rhythmic footwork and mythological storytelling.",
            "duration": "1 hour per session",
            "fee": 1000,
        },
        {
            "name": "Folk Dance",
            "description": "Lively traditional dance forms performed during festivals and cultural events.",
            "duration": "1 hour per session",
            "fee": 800,
        },
    ]

    course_objs = {}
    for item in courses_data:
        course_obj, _ = Course.objects.get_or_create(
            name=item["name"],
            defaults={
                "description": item["description"],
                "duration": item["duration"],
                "fee": item["fee"],
                "is_active": True,
            },
        )
        course_objs[item["name"]] = course_obj

    # Timetable slots from the original hardcoded data.
    slots_by_course = {
        "Bharatanatyam": [
            ("Monday", "5 PM - 6 PM"),
            ("Thursday", "5 PM - 6 PM"),
        ],
        "Mohiniyattam": [
            ("Tuesday", "5 PM - 6 PM"),
            ("Friday", "5 PM - 6 PM"),
        ],
        "Kuchipudi": [
            ("Wednesday", "5 PM - 6 PM"),
            ("Saturday", "4 PM - 5 PM"),
        ],
        "Folk Dance": [
            ("Saturday", "5 PM - 6 PM"),
            ("Sunday", "4 PM - 5 PM"),
        ],
    }

    modes = ["Online", "Offline"]
    for course_name, slots in slots_by_course.items():
        course = course_objs[course_name]
        for day, time in slots:
            for mode in modes:
                Timetable.objects.get_or_create(
                    course=course,
                    day=day,
                    time=time,
                    mode=mode,
                )

    # Instructor seed (based on original hardcoded instructor dict).
    Instructor.objects.get_or_create(
        name="Kalamandalam Krishnendu Nair",
        defaults={
            "specialization": "Bharatanatyam, Mohiniyattam, Kuchipudi",
            "experience": "16+ Years",
            "about": "Dedicated classical dance artist with over 16 years of experience.",
            "education_details": "Kerala Kalamandalam\nRLV College, Tripunithura",
            "performance_details": "Performed across Kerala and Kuwait",
            "teaching_details": "Founder of Samskriti Nrithakalari",
            "contact_phone": "9544839846",
            "contact_email": "knair.ktm@gmail.com",
            "location": "Aluva",
        },
    )


def noop(apps, schema_editor):
    # No-op on reverse; this seed migration is intended to be additive.
    return


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_instructor_alter_course_options_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_academy_data, reverse_code=noop),
    ]

