# Generated by Django 5.0.2 on 2026-03-19 15:40

import django.db.models.deletion
from django.db import migrations, models


def clear_selected_course_values(apps, schema_editor):
    """
    Your old database stored `UserProfile.selected_course` as a plain string
    (course name). After the refactor it becomes a ForeignKey, so old values
    would fail FK constraints during migration.

    To keep the migration non-interactive and reliable, we clear the
    existing `selected_course` values here (students will re-select course
    in the Join flow after migration).
    """

    UserProfile = apps.get_model("core", "UserProfile")
    for profile in UserProfile.objects.all():
        # Field is nullable at this stage; setting to NULL keeps constraints valid.
        profile.selected_course = None
        profile.save(update_fields=["selected_course"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260317_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialization', models.TextField(blank=True)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('about', models.TextField(blank=True)),
                ('education_details', models.TextField(blank=True)),
                ('performance_details', models.TextField(blank=True)),
                ('teaching_details', models.TextField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__username']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='class_day',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='class_mode',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='class_time',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.DecimalField(decimal_places=0, default=1000, max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='Course', max_length=100),
        ),
        migrations.RunPython(clear_selected_course_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='userprofile',
            name='selected_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_students', to='core.course'),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=50)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='core.course')),
            ],
            options={
                'ordering': ['course__name', 'day', 'time'],
                'unique_together': {('course', 'day', 'time', 'mode')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selected_timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_students', to='core.timetable'),
        ),
    ]
