# Generated by Django 5.0.2 on 2026-03-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_course_image_instructor_image_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/'),
        ),
    ]
